-- Delete existing categories
DELETE FROM story_categories;
DELETE FROM categories;

-- Insert the real categories from erota.ai
INSERT INTO categories (name, slug) VALUES
  ('Affair', 'affair'),
  ('Airplane', 'airplane'),
  ('Amateur', 'amateur'),
  ('Anal', 'anal'),
  ('Ancient', 'ancient'),
  ('Asian', 'asian'),
  ('Ass eating', 'ass-eating'),
  ('BBC', 'bbc'),
  ('BBW', 'bbw'),
  ('BDSM', 'bdsm'),
  ('Bath', 'bath'),
  ('Bathroom', 'bathroom'),
  ('Beach', 'beach'),
  ('Bi Female', 'bi-female'),
  ('Bi Male', 'bi-male'),
  ('Bisexual', 'bisexual'),
  ('Black', 'black'),
  ('Blonde', 'blonde'),
  ('Bondage', 'bondage'),
  ('Buttplug', 'buttplug'),
  ('Car', 'car'),
  ('Car Sex', 'car-sex'),
  ('Cartoon', 'cartoon'),
  ('Chastity', 'chastity'),
  ('Chastity Cage', 'chastity-cage'),
  ('Cheating', 'cheating'),
  ('Cheerleader', 'cheerleader'),
  ('Coffeeshop', 'coffeeshop'),
  ('College', 'college'),
  ('Cosplay', 'cosplay'),
  ('Cuckold', 'cuckold'),
  ('Cuckquean', 'cuckquean'),
  ('Cum', 'cum'),
  ('Cunnilingus', 'cunnilingus'),
  ('Danger', 'danger'),
  ('Dildo', 'dildo'),
  ('Domination', 'domination'),
  ('European', 'european'),
  ('Explicit Image', 'explicit-image'),
  ('Explicit Video', 'explicit-video'),
  ('Femboy', 'femboy'),
  ('Femdom', 'femdom'),
  ('Filming', 'filming'),
  ('First Time', 'first-time'),
  ('Fisting', 'fisting'),
  ('Gamer', 'gamer'),
  ('Gay', 'gay'),
  ('Girlfriend', 'girlfriend'),
  ('Group', 'group'),
  ('Group Sex', 'group-sex'),
  ('Gym', 'gym'),
  ('Halloween', 'halloween'),
  ('Hotel', 'hotel'),
  ('Hotwife', 'hotwife'),
  ('Indian', 'indian'),
  ('Lactation', 'lactation'),
  ('Latin', 'latin'),
  ('Latina', 'latina'),
  ('Lesbian', 'lesbian'),
  ('Masturbation', 'masturbation'),
  ('Muscular', 'muscular'),
  ('Office', 'office'),
  ('OnlyFans', 'onlyfans'),
  ('Oral', 'oral'),
  ('Outdoors', 'outdoors'),
  ('Pegging', 'pegging'),
  ('Public', 'public'),
  ('Religious', 'religious'),
  ('Rimming', 'rimming'),
  ('Sauna', 'sauna'),
  ('Selfie', 'selfie'),
  ('Sissy', 'sissy'),
  ('Small Penis', 'small-penis'),
  ('Space', 'space'),
  ('Strapon', 'strapon'),
  ('Student', 'student'),
  ('Submission', 'submission'),
  ('Teacher', 'teacher'),
  ('Threesome', 'threesome'),
  ('Toilet', 'toilet'),
  ('Trans Woman', 'trans-woman'),
  ('Travel', 'travel'),
  ('Tribadism', 'tribadism'),
  ('Twink', 'twink'),
  ('Workplace', 'workplace');